<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>java</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Java</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*/.*\n</string>
			<key>name</key>
			<string>invalid.illegal.stray-comment-end.java</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.java</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&gt;\\\s*\n)</string>
					<key>name</key>
					<string>punctuation.separator.continuation.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0[xX][0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))([eE][+-]?[0-9]+)?)[lLfF]?\b</string>
			<key>name</key>
			<string>constant.numeric.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|case|continue|default|do|else|for|goto|if|return|switch|throw|while)\b</string>
			<key>name</key>
			<string>keyword.control.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abstract|final|native|private|protected|public|static|synchronized|transient|volatile)\b</string>
			<key>name</key>
			<string>keyword.modifiers.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assert|catch|finally|import|instaceof|package|new|throws|try)\b</string>
			<key>name</key>
			<string>keyword.other.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(this|super)\b</string>
			<key>name</key>
			<string>variable.language.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\W\s]@[a-zA-Z]+</string>
			<key>name</key>
			<string>entity.other.annotation.java</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.java</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.java</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other.java</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.java</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(class)\s+(\w+)(\s+(extends|implements)\s+(\w+))?</string>
			<key>name</key>
			<string>meta.class.java</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.interface.java</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.interface.java</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other.java</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.java</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(interface)\s+(\w+)(\s+(extends|implements)\s+(\w+))?</string>
			<key>name</key>
			<string>meta.interface.java</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.enum.java</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.enum.java</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(enum)\s+(\w+)</string>
			<key>name</key>
			<string>meta.enum.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z_]+\b</string>
			<key>name</key>
			<string>support.constant.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|[a-z\.]+\.)[A-Z]\w+\b</string>
			<key>name</key>
			<string>support.type.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(boolean|byte|char|double|float|int|long|short|void)\b</string>
			<key>name</key>
			<string>storage.type.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*\()</string>
			<key>name</key>
			<string>entity.name.function.java</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.java</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.java</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(this|super)\b</string>
			<key>name</key>
			<string>variable.language.java</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[\\'"bfnrt]|u[0-9a-fA-F]{4}</string>
					<key>name</key>
					<string>constant.character.escape.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.java</string>
				</dict>
			</array>
		</dict>
		<key>string_placeholder</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%[,+-]*(([0-9]+\.?[0-9]*)|(\.[0-9]+))?([%dfn]|t[BdDelmMpyY])</string>
					<key>name</key>
					<string>constant.other.placeholder.java</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.java</string>
	<key>uuid</key>
	<string>E6E61257-73B9-42AC-B518-3BBB169EE10A</string>
</dict>
</plist>
